version: '3.8'

services:
  jupyter:
    image: continuumio/anaconda3
    ports:
      - 8888:8888
    volumes:
      - ./work:/work
    working_dir: /work
    command: jupyter lab --allow-root --ip=0.0.0.0
